#ifndef MOZ_FFVPX_CONFIG_COMMON_H
#define MOZ_FFVPX_CONFIG_COMMON_H

#include "defaults_disabled.h"

#ifndef CONFIG_H263_VAAPI_HWACCEL
#define CONFIG_H263_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_H263_VIDEOTOOLBOX_HWACCEL
#define CONFIG_H263_VIDEOTOOLBOX_HWACCEL 0
#endif
#ifndef CONFIG_H264_D3D11VA2_HWACCEL
#define CONFIG_H264_D3D11VA2_HWACCEL 0
#endif
#ifndef CONFIG_H264_D3D11VA_HWACCEL
#define CONFIG_H264_D3D11VA_HWACCEL 0
#endif
#ifndef CONFIG_H264_DXVA2_HWACCEL
#define CONFIG_H264_DXVA2_HWACCEL 0
#endif
#ifndef CONFIG_H264_NVDEC_HWACCEL
#define CONFIG_H264_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_H264_VAAPI_HWACCEL
#define CONFIG_H264_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_H264_VDPAU_HWACCEL
#define CONFIG_H264_VDPAU_HWACCEL 0
#endif
#ifndef CONFIG_H264_VIDEOTOOLBOX_HWACCEL
#define CONFIG_H264_VIDEOTOOLBOX_HWACCEL 0
#endif
#ifndef CONFIG_HEVC_D3D11VA2_HWACCEL
#define CONFIG_HEVC_D3D11VA2_HWACCEL 0
#endif
#ifndef CONFIG_HEVC_D3D11VA_HWACCEL
#define CONFIG_HEVC_D3D11VA_HWACCEL 0
#endif
#ifndef CONFIG_HEVC_DXVA2_HWACCEL
#define CONFIG_HEVC_DXVA2_HWACCEL 0
#endif
#ifndef CONFIG_HEVC_NVDEC_HWACCEL
#define CONFIG_HEVC_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_HEVC_VAAPI_HWACCEL
#define CONFIG_HEVC_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_HEVC_VDPAU_HWACCEL
#define CONFIG_HEVC_VDPAU_HWACCEL 0
#endif
#ifndef CONFIG_HEVC_VIDEOTOOLBOX_HWACCEL
#define CONFIG_HEVC_VIDEOTOOLBOX_HWACCEL 0
#endif
#ifndef CONFIG_MJPEG_NVDEC_HWACCEL
#define CONFIG_MJPEG_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_MJPEG_VAAPI_HWACCEL
#define CONFIG_MJPEG_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_MPEG1_NVDEC_HWACCEL
#define CONFIG_MPEG1_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_MPEG1_VDPAU_HWACCEL
#define CONFIG_MPEG1_VDPAU_HWACCEL 0
#endif
#ifndef CONFIG_MPEG1_VIDEOTOOLBOX_HWACCEL
#define CONFIG_MPEG1_VIDEOTOOLBOX_HWACCEL 0
#endif
#ifndef CONFIG_MPEG1_XVMC_HWACCEL
#define CONFIG_MPEG1_XVMC_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_D3D11VA2_HWACCEL
#define CONFIG_MPEG2_D3D11VA2_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_D3D11VA_HWACCEL
#define CONFIG_MPEG2_D3D11VA_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_DXVA2_HWACCEL
#define CONFIG_MPEG2_DXVA2_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_NVDEC_HWACCEL
#define CONFIG_MPEG2_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_VAAPI_HWACCEL
#define CONFIG_MPEG2_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_VDPAU_HWACCEL
#define CONFIG_MPEG2_VDPAU_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_VIDEOTOOLBOX_HWACCEL
#define CONFIG_MPEG2_VIDEOTOOLBOX_HWACCEL 0
#endif
#ifndef CONFIG_MPEG2_XVMC_HWACCEL
#define CONFIG_MPEG2_XVMC_HWACCEL 0
#endif
#ifndef CONFIG_MPEG4_NVDEC_HWACCEL
#define CONFIG_MPEG4_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_MPEG4_VAAPI_HWACCEL
#define CONFIG_MPEG4_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_MPEG4_VDPAU_HWACCEL
#define CONFIG_MPEG4_VDPAU_HWACCEL 0
#endif
#ifndef CONFIG_MPEG4_VIDEOTOOLBOX_HWACCEL
#define CONFIG_MPEG4_VIDEOTOOLBOX_HWACCEL 0
#endif
#ifndef CONFIG_VC1_D3D11VA2_HWACCEL
#define CONFIG_VC1_D3D11VA2_HWACCEL 0
#endif
#ifndef CONFIG_VC1_D3D11VA_HWACCEL
#define CONFIG_VC1_D3D11VA_HWACCEL 0
#endif
#ifndef CONFIG_VC1_DXVA2_HWACCEL
#define CONFIG_VC1_DXVA2_HWACCEL 0
#endif
#ifndef CONFIG_VC1_NVDEC_HWACCEL
#define CONFIG_VC1_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_VC1_VAAPI_HWACCEL
#define CONFIG_VC1_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_VC1_VDPAU_HWACCEL
#define CONFIG_VC1_VDPAU_HWACCEL 0
#endif
#ifndef CONFIG_VP8_NVDEC_HWACCEL
#define CONFIG_VP8_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_VP8_VAAPI_HWACCEL
#define CONFIG_VP8_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_VP9_D3D11VA2_HWACCEL
#define CONFIG_VP9_D3D11VA2_HWACCEL 0
#endif
#ifndef CONFIG_VP9_D3D11VA_HWACCEL
#define CONFIG_VP9_D3D11VA_HWACCEL 0
#endif
#ifndef CONFIG_VP9_DXVA2_HWACCEL
#define CONFIG_VP9_DXVA2_HWACCEL 0
#endif
#ifndef CONFIG_VP9_NVDEC_HWACCEL
#define CONFIG_VP9_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_VP9_VAAPI_HWACCEL
#define CONFIG_VP9_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_VP9_VDPAU_HWACCEL
#define CONFIG_VP9_VDPAU_HWACCEL 0
#endif
#ifndef CONFIG_WMV3_D3D11VA2_HWACCEL
#define CONFIG_WMV3_D3D11VA2_HWACCEL 0
#endif
#ifndef CONFIG_WMV3_D3D11VA_HWACCEL
#define CONFIG_WMV3_D3D11VA_HWACCEL 0
#endif
#ifndef CONFIG_WMV3_DXVA2_HWACCEL
#define CONFIG_WMV3_DXVA2_HWACCEL 0
#endif
#ifndef CONFIG_WMV3_NVDEC_HWACCEL
#define CONFIG_WMV3_NVDEC_HWACCEL 0
#endif
#ifndef CONFIG_WMV3_VAAPI_HWACCEL
#define CONFIG_WMV3_VAAPI_HWACCEL 0
#endif
#ifndef CONFIG_WMV3_VDPAU_HWACCEL
#define CONFIG_WMV3_VDPAU_HWACCEL 0
#endif

#endif
